// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Ticket struct {
	ID         uuid.UUID
	TrainID    uuid.UUID
	UserID     uuid.UUID
	SeatNumber int32
	BookedAt   sql.NullTime
}

type Train struct {
	ID         uuid.UUID
	Name       string
	TotalSeats int32
}

type User struct {
	ID       uuid.UUID
	Email    string
	Password string
}
