// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Ticket struct {
	ID         string
	TrainID    string
	UserID     string
	SeatNumber int64
	BookedAt   sql.NullTime
}

type Train struct {
	ID         string
	Name       string
	TotalSeats int64
}

type User struct {
	ID       string
	Email    string
	Password string
}
